# Generated by Django 3.2.7 on 2021-09-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_productmovement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMovement',
        ),
    ]
